---
framework: mocha  
preRun:
  command:
    - npm install  
preMerge:
  pattern:
    - "./test/acceptance/cookies.js"
postMerge:
  pattern: 
    - "./test/acceptance/cookies.js"
postRun:
  command:
    - node --version
configFile: mocharc.yml
